### ISSUE TITLE
Factor out `streaming-attoparsec`

### ISSUE THREAD

**Issue by fosskers** [ocharles/streaming-utils#1]
And make it use the latest `streaming`, `streaming-bytestring`, and `attoparsec`.

I'll take care of this myself, if it's not on anyone's task list. How would I go about donating the repo to the `haskell-streaming` org?

**Comment by ocharles** [comment]
In the settings tag of the repository you wish to transfer there should be the option to transfer it. You'll need to that, and then @andrewthad will need to re-grant you admin rights.

**Comment by fosskers** [comment]
WIP: https://github.com/fosskers/streaming-attoparsec

**Comment by fosskers** [comment]
First pass is complete, I'll transfer it.

I've added a test suite, improved the docs, ensured compatibility with the latest versions of other `streaming` libs, and fixed the [left-biased `Either` issue](https://github.com/michaelt/streaming-utils/issues/1).

**Comment by fosskers** [comment]
Trying to transfer it gave me:

>  You don’t have the permission to create repositories on haskell-streaming 

I'm not in the org, so that makes sense.

**Comment by ocharles** [comment]
Ok, this might need Andrew to add you as a member of the org first then.

**Comment by fosskers** [comment]
Pinging @andrewthad :)

**Comment by andrewthad** [comment]
I've added @fosskers as a member.
