### ISSUE TITLE
Where is the upstream repo+branch for streaming-utils 0.2.1.0 on hackage?

### ISSUE THREAD

**Issue by vdukhovni** [ocharles/streaming-utils#10]
This repository seems to have 0.2.0.0.  There's a 0.2.1.0 on hackage.  What is its provenance?

**Comment by ocharles** [comment]
It looks like I cut that release, so I'll sort this out. Hopefully just forgot a push!

**Comment by ocharles** [comment]
Sorry it took so long, but this is now pushed, along with the corresponding tag.
