### ISSUE TITLE
Fails to build with GHC 9.2.2

### ISSUE THREAD

**Issue by arjunkathuria** [ocharles/streaming-utils#11]
This package seems to fail to build with the new GHC version 9.2.2

i'll update this document with the exact error when i hop back on the project i was working on.

Opening the issue now so that i remember to.

**Comment by ocharles** [comment]
I think this is now fixed, but if you're still having problems, please reopen this issue. Note I've just pushed 0.2.2.0 to Hackage, which you may need.
