### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by ocharles** [ocharles/streaming-utils#2]
Could we have a new release? https://github.com/haskell-streaming/streaming-utils/commit/507ebc629c6b40179af5707eb337eff2fd4c3eef was committed in January but never made it to Hackage. I'm happy to help be a maintainer.

**Comment by chessai** [comment]
I can add you as a maintainer to streaming-utils on Hackage. What is your Hackage username?

**Comment by ocharles** [comment]
Thanks. I'm `OliverCharles`.

**Comment by chessai** [comment]
@ocharles you have been added as a maintainer to streaming-utils!
